### ISSUE TITLE
Dependency Issue - incompatible with BigInt 2.x

### ISSUE THREAD

**Issue by fpieper** [nathanjohnson320/base58#4]
If BigInt 2.x is required by another package it is not possible to install base58.

I copied the Base58.elm file and tested it with BigInt 2.0.1, it seems to work.
I just needed to change `BigInt.fromString` to `BigInt.fromIntString` in the encoding example, but the base58 library itself didn't need to be changed.

Would be great if we could fix the dependency (BigInt 2.x is more or less the new standard).

To reproduce to demonstrate that installing this package tries to downgrade BigInt to 1.x if BigInt 2.x is installed:
```
mkdir testelm
cd testelm
elm init
elm install cmditch/elm-bigint
elm install nathanjohnson320/base58
```
Thanks in advance 👍

**Comment by nathanjohnson320** [comment]
Hi I updated to bigint 2 and the tests still work so I think it's ok. Let me know if it works for you :+1:

**Comment by fpieper** [comment]
Thank you very much for your quick and helpful response.
It is fixed now and I was able to install and use the library regularly 👍 .
